name: .NET

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add GitHub Packages NuGet source
      run: dotnet nuget add source --username caleborchard --password ${{ github.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/caleborchard/index.json"
    - name: Restore dependencies
      run: dotnet restore BabyStepsMultiplayerServer/BabyStepsMultiplayerServer.csproj
    - name: Build
      run: dotnet build BabyStepsMultiplayerServer/BabyStepsMultiplayerServer.csproj --no-restore
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BabyStepsMultiplayerServer-linux
        path: BabyStepsMultiplayerServer/bin/Debug/net8.0/

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add GitHub Packages NuGet source
      run: dotnet nuget add source --username caleborchard --password ${{ github.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/caleborchard/index.json"
    - name: Restore dependencies
      run: dotnet restore BabyStepsMultiplayerServer/BabyStepsMultiplayerServer.csproj
    - name: Build
      run: dotnet build BabyStepsMultiplayerServer/BabyStepsMultiplayerServer.csproj --no-restore
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BabyStepsMultiplayerServer-windows
        path: BabyStepsMultiplayerServer/bin/Debug/net8.0/
