name: .NET

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read
  packages: write
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BabyStepsMultiplayerServer-linux
        path: BabyStepsMultiplayerServer/bin/Debug/net8.0/

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BabyStepsMultiplayerServer-windows
        path: BabyStepsMultiplayerServer/bin/Debug/net8.0/
